modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="pmtinfai"
version="1.0.0"
displayName="PM_TINF19AI2"
credits=""
displayURL=""
authors="Gnuh"

[[dependencies.pmtinfai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



