modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="pmtinfai"
version="${version}"
displayName="Minekraft Logik Gatter"
credits="Created by a group of students from Germany"
displayURL="https://minekraft-logik-gatter.de"
logoFile="logo.png"
authors="Hung, Silas, Tim, Leander, Oli, Jannik"
description='''
    Coolest mod on earth.
    '''

[[dependencies.pmtinfai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



